// Copyright (c) 2015, 2025, Oracle and/or its affiliates.
//-----------------------------------------------------------------------------
//
// This software is dual-licensed to you under the Universal Permissive License
// (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl and Apache License
// 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose
// either license.
//
// If you elect to accept the software under the Apache License, Version 2.0,
// the following applies:
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-----------------------------------------------------------------------------
// 

import { Oracledb } from "../internal/core";
import { BulkUpdate } from "../transaction/bulk";
import { DocumentData } from "../types/common";


/**
 * Adds a new document to the specified CollectionReference with the given data.
 * The document ID will be automatically generated by Oracledb.
 *
 * @typeParam AppModelType - The application model type for type safety.
 * @typeParam DbModelType - The Oracledb database type, defaults to DocumentData.
 *
 * @param reference - The CollectionReference where the document will be added.
 * @param data - An object containing the data for the new document.
 *
 * @returns A Promise that resolves with a DocumentReference pointing to the newly
 * created document.
 *
 * @example
 * import { collection, addDoc } from "fusabase/oracledb";
 * 
 * interface User {
 *   name: string;
 *   age: number;
 * }
 * 
 * async function addUser() {
 *   const usersRef = collection(db, "users");
 *   const newUserRef = await addDoc<User, DocumentData>(usersRef, {
 *     name: "Alice",
 *     age: 25
 *   });
 *   console.log("Added user with ID:", newUserRef.id);
 * }
 */
export declare function addDoc<
  AppModelType,
  DbModelType extends DocumentData
>(
  reference: CollectionReference<AppModelType, DbModelType>,
  data: WithFieldValue<AppModelType>
): Promise<DocumentReference<AppModelType, DbModelType>>;


/**
 * Deletes the document referred to by the specified DocumentReference.
 *
 * @typeParam AppModelType - The application model type.
 * @typeParam DbModelType - The Oracledb database type, defaults to DocumentData.
 *
 * @param reference - The DocumentReference to delete.
 * @returns A Promise resolved once the document is successfully deleted.
 *
 * @example
 * import { deleteDoc, doc } from "fusabase/oracledb";
 *
 * async function removeUser(userId: string) {
 *   const userRef = doc(db, "users", userId);
 *   await deleteDoc(userRef);
 *   console.log("User deleted");
 * }
 */
export declare function deleteDoc<
  AppModelType,
  DbModelType extends DocumentData
>(reference: DocumentReference<AppModelType, DbModelType>): Promise<void>;

/**
 * Writes data to the specified DocumentReference with options for merging.
 *
 * @param reference - The DocumentReference to write.
 * @param data - Partial data to merge with the existing document.
 * @param options - Configuration object for merge behavior.
 * @returns A Promise resolved once the data is successfully written.
 *
 * @example
 * import { setDoc, doc } from "fusabase/oracledb";
 *
 * async function updateUser(userId: string) {
 *   const userRef = doc(db, "users", userId);
 *   await setDoc(userRef, { age: 26 }, { merge: true });
 *   console.log("User updated");
 * }
 */
export declare function setDoc<
  AppModelType,
  DbModelType extends DocumentData
>(
  reference: DocumentReference<AppModelType, DbModelType>,
  data: PartialWithFieldValue<AppModelType>,
  options: SetOptions
): Promise<void>;

/**
 * Updates fields in the specified document.
 *
 * @param reference - The DocumentReference to update.
 * @param data - An object containing the fields and values to update.
 * @returns A Promise resolved once the update succeeds.
 *
 * @example
 * import { updateDoc, doc } from "fusabase/oracledb";
 *
 * async function updateUserAge(userId: string) {
 *   const userRef = doc(db, "users", userId);
 *   await updateDoc(userRef, { age: 27 });
 *   console.log("User age updated");
 * }
 */
export declare function updateDoc<
  AppModelType,
  DbModelType extends DocumentData
>(
  reference: DocumentReference<AppModelType, DbModelType>,
  data: UpdateData<DbModelType>
): Promise<void>;

/**
 * Updates fields in the specified document with field/value pairs.
 *
 * @param reference - The DocumentReference to update.
 * @param field - The first field to update.
 * @param value - The value for the first field.
 * @param moreFieldsAndValues - Additional field/value pairs to update.
 * @returns A Promise resolved once the update succeeds.
 *
 * @example
 * import { updateDoc, doc, FieldPath } from "fusabase/oracledb";
 *
 * async function updateUserMultipleFields(userId: string) {
 *   const userRef = doc(db, "users", userId);
 *   await updateDoc(userRef, "age", 28, "status", "active");
 *   console.log("User fields updated");
 * }
 */
export declare function updateDoc<
  AppModelType,
  DbModelType extends DocumentData
>(
  reference: DocumentReference<AppModelType, DbModelType>,
  field: string | FieldPath,
  value: unknown,
  ...moreFieldsAndValues: unknown[]
): Promise<void>;

/**
 * Writes data to the specified DocumentReference. Creates the document if it doesn't exist.
 *
 * @param reference - The DocumentReference to write.
 * @param data - An object containing the data to write.
 * @returns A Promise resolved once the data is successfully written.
 *
 * @example
 * import { setDoc, doc } from "fusabase/oracledb";
 *
 * async function createUser(userId: string) {
 *   const userRef = doc(db, "users", userId);
 *   await setDoc(userRef, { name: "Alice", age: 25 });
 *   console.log("User created or overwritten");
 * }
 */
export declare function setDoc<
  AppModelType,
  DbModelType extends DocumentData
>(
  reference: DocumentReference<AppModelType, DbModelType>,
  data: WithFieldValue<AppModelType>
): Promise<void>;

/**
 * Method to get `BulkUpdate` instance for the path.
 * 
 * @param {String} path
 * @return {BulkUpdate}
 */
export function updateDocs<
  AppModelType,
  DbModelType extends DocumentData
>(
  reference: Oracledb,
  path?: string
): BulkUpdate<AppModelType, DbModelType>;
